apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-peliculas-favoritos-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-peliculas-favoritos-backend
  template:
    metadata:
      labels:
        app: ms-peliculas-favoritos-backend
    spec:
      containers:
        - name: ms-peliculas-favoritos-backend-container
          image: anthonyponte/ms-peliculas-favoritos-backend:1.0.0
          args:
            - "--spring.config.additional-location=file:/config/"
          ports:
            - containerPort: 9094
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9094
            initialDelaySeconds: 400
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9094
            initialDelaySeconds: 105
            periodSeconds: 10
            timeoutSeconds: 10
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "200m"
              memory: "600Mi"
          volumeMounts:
            - name: ms-peliculas-favoritos-backend-volume
              mountPath: /config/
              subPath: application.yml
      volumes:
        - name: ms-peliculas-favoritos-backend-volume
          configMap:
            name: ms-peliculas-favoritos-backend-configmap
            items:
              - key: application.yml
                path: application.yml